development:
  adapter: postgresql
  database: groupmuse_development
  host: localhost

test: 
  adapter: postgresql
  database: groupmuse_test
  host: localhost

production:
  adapter: postgresql
  database: groupmuse_development
  host: localhost
